FROM raspian:4.9

RUN apt-get update && apt-get install -y --no-install-recommends \
RUN apt-get install -y dirmngr
RUN bash -c  'echo "deb https://raspbian.snips.ai/$(lsb_release -cs) stable main" > /etc/apt/sources.list.d/snips.list'
RUN apt-key adv --keyserver pgp.mit.edu --recv-keys D4F50CDCA10A2849

RUN apt-get update
RUN apt-get install -y snips-platform-voice

RUN rm -r /usr/share/snips/assistant

COPY assistant /usr/share/snips/assistant

RUN systemctl restart "snips*"
